export const MODE = {
  NONE: 'NONE',
  WAIT_DATA: 'WAIT_DATA',
  IDLE: 'IDLE',
  LEARNING: 'LEARNING',
  CHECKPOINT: 'CHECKPOINT',
  COMPLETED: 'COMPLETED',
  TIMEOUT: 'TIMEOUT',
  FAILED: 'FAILED',
  SYSTEM_FAILED: 'SYSTEM_FAILED'
}

export const COOPERATIVE = {
  '1v1': '1v1',
  'nv1': 'nv1',
  'nvm': 'nvm'
}