version: "3"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-18-bullseye
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  ethereum:
    image: ethereum/client-go
    platform: linux/amd64
    command: >
      --dev --datadir /root/.ethereum
      --ws --ws.addr "0.0.0.0" --ws.api "eth,web3,net" --ws.origins "*"
    volumes:
      - /root/.ethereum
