name: Create and publish a NodeJS bundle

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release-bundle:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build NodeJS bundle
        run: npm run build

      - name: Package NodeJS bundle and config
        run: cd dist && zip -r emeth-node bundle.js config

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: dist/emeth-node.zip
